-- MySQL Script generated by MySQL Workbench
-- dom 10 out 2021 12:52:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exemplos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exemplos` ;

-- -----------------------------------------------------
-- Schema exemplos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exemplos` ;
USE `exemplos` ;

-- -----------------------------------------------------
-- Table `exemplos`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exemplos`.`Cliente` (
  `Cliente_id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cliente_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exemplos`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exemplos`.`Telefone` (
  `Cliente_id` INT NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`),
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `exemplos`.`Cliente` (`Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exemplos`.`Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exemplos`.`Email` (
  `Cliente_id` INT NOT NULL,
  `Cliente_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cliente_email`),
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `exemplos`.`Cliente` (`Cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exemplos`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exemplos`.`Funcionario` (
  `Funcionario_id` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Funcionario_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `exemplos`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `exemplos`;
INSERT INTO `exemplos`.`Cliente` (`Cliente_id`, `Nome`) VALUES (1, 'Sheldon Cooper');
INSERT INTO `exemplos`.`Cliente` (`Cliente_id`, `Nome`) VALUES (2, 'Amy Farrah Fowler	');
INSERT INTO `exemplos`.`Cliente` (`Cliente_id`, `Nome`) VALUES (3, 'Leonard Hofstadter');
INSERT INTO `exemplos`.`Cliente` (`Cliente_id`, `Nome`) VALUES (4, 'Bernadette Maryann');

COMMIT;


-- -----------------------------------------------------
-- Data for table `exemplos`.`Telefone`
-- -----------------------------------------------------
START TRANSACTION;
USE `exemplos`;
INSERT INTO `exemplos`.`Telefone` (`Cliente_id`, `Numero`) VALUES (1, '(19) 16044-3249');
INSERT INTO `exemplos`.`Telefone` (`Cliente_id`, `Numero`) VALUES (2, '(73) 45578-8629');
INSERT INTO `exemplos`.`Telefone` (`Cliente_id`, `Numero`) VALUES (3, '(23) 57692-8688');
INSERT INTO `exemplos`.`Telefone` (`Cliente_id`, `Numero`) VALUES (4, '(62) 19832-5762');

COMMIT;


-- -----------------------------------------------------
-- Data for table `exemplos`.`Email`
-- -----------------------------------------------------
START TRANSACTION;
USE `exemplos`;
INSERT INTO `exemplos`.`Email` (`Cliente_id`, `Cliente_email`) VALUES (1, 'protoncooper@scemail.com');
INSERT INTO `exemplos`.`Email` (`Cliente_id`, `Cliente_email`) VALUES (2, 'badgirl@scemail.com');
INSERT INTO `exemplos`.`Email` (`Cliente_id`, `Cliente_email`) VALUES (3, 'luckyman@scemail.com');
INSERT INTO `exemplos`.`Email` (`Cliente_id`, `Cliente_email`) VALUES (4, 'candybern@mbmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `exemplos`.`Funcionario`
-- -----------------------------------------------------
START TRANSACTION;
USE `exemplos`;
INSERT INTO `exemplos`.`Funcionario` (`Funcionario_id`, `Nome`) VALUES (1, 'Stuart Bloom');
INSERT INTO `exemplos`.`Funcionario` (`Funcionario_id`, `Nome`) VALUES (2, 'Sheldon Cooper');
INSERT INTO `exemplos`.`Funcionario` (`Funcionario_id`, `Nome`) VALUES (3, 'Leonard Hofstadter');
INSERT INTO `exemplos`.`Funcionario` (`Funcionario_id`, `Nome`) VALUES (4, 'Raj Koothrappali');

COMMIT;

